### PR TITLE
Update xcodeproj

### PR DESCRIPTION
**Pull request by keith**
These files are written when the project is opened

### CODE REVIEW

**Comment by keith** [comment]
@fangpenlin have a minute to review this? 🙏

**Comment by fangpenlin** [comment]
@keith while your PR looks good to me, but for now I don't work at Envoy and I don't have the permission to merge it and publish it, you may ask @LFabien for help.

@LFabien maybe you can help him on this?

**Comment by keith** [comment]
Thanks!


--
Keith Smiley

**Comment by LFabien** [comment]
Thanks @keith !

**Pull request merged**
