### PR TITLE
[Bugfix] Crashes when reading the body in Release configurations

### LINKED ISSUE #96: Crashes when reading the body in Release configurations
# Description of the issue

We are using Embassy to mock our internals API for testing purposes and since we are upgrading our environment (Xcode 11.3.1 to Xcode 12.4) we are experiencing some bugs in our tests in release configuration.

After digging into the issue, we cloned the repository and try to run the unit tests in release and it seems that the library's tests are having the same issue as we do, the tests on the body features are crashing in release (``HTTPServerTests.testPostBody()``, ``HTTPServerTests.testPostWithInitialBody()`` for instance).

[``SelectorEventLoop+177``](https://github.com/envoy/Embassy/blob/065b6ce52596bd06b867cfe17fea2c56dcb53b30/Sources/SelectorEventLoop.swift#L177)
Capture d’écran 2021-04-22 à 14 17 49

Has anyone experiencing this during the transition to Xcode 12?

# Environment

macOS Big Sur 11.2.3 (intel)
Xcode 12.4 (12D4e)
Embassy 4.1.3

# Reproduction

Run these unit tests in release configuration:
- ``HTTPServerTests.testPostBody()``
- ``HTTPServerTests.testPostWithInitialBody()``

Both tests shall fail.

### PR DESCRIPTION
**Pull request by ArnaudWurmel**
Fixes #96 

# Explanation

When the ``_value`` is set to a new value, the closure's parameter ``value`` is freed from memory. When this freed value was returned to the SelectorEventLoop, the app crashed. 

To avoid this, I suggest to keep a strong reference to the value object, that way it won't be deleted.

### CODE REVIEW

**Comment by Goos** [comment]
Hey @ArnaudWurmel – thanks for looking into this, and sorry for not responding sooner. 

Have you verified that this solves the crash you're seeing? I would have assumed that the value would live until the end of the closure as it being passed in as an argument should increment its retain count.

**Comment by ArnaudWurmel** [comment]
Hey @Goos,

We were using this branch temporally and it allowed us to read the body without having crashes. However, we shortly faced another crash when we launches multiple uitests on iOS 14 (the crash occurs after ~15 tests).

We didn't explore much the second issue because it could come from our end since all Embassy tests passes.

> I would have assumed that the value would live until the end of the closure as it being passed in as an argument should increment its retain count

I thought the same, when I was trying to debug this, I displayed the value at each step and after the assignment of the ``_value`` property, we couldn't access to the closure's parameter ``value`` anymore. So I come with this fix but the issue could be deeper than that.

**Comment by Goos** [comment]
@ArnaudWurmel I just merged [another fix](https://github.com/envoy/Embassy/pull/91) related causing a `BAD_ACCESS` of the body, would you mind testing the latest master and seeing if it fixed your crash?

**Comment by ArnaudWurmel** [comment]
Still have the same issue, try to run the unit tests of Embassy (xcode 12) in Release mode (Edit scheme > Embassy-iOS > Test > Info > Build Configuration = Release) and enable testability in release (Target Embassy-iOS > Build Settings > Enabled Testability > Release = Yes)

**Review by fsafak453 — APPROVED** [review]

**Comment by dubadub** [comment]
@Goos are there any code issues we need to fix to merge this PR?

Re: https://github.com/cooklang/CookCLI/issues/33.

**Comment by geofstro** [comment]
I don’t know if this is related; but I’m getting a crash under Monterey  with the latest version of xCode 13.2.1

It happens at the fatalError line in “Transport” following “default:"

} catch let OSError.ioError(number, message) {
            switch number {
            case EAGAIN:
                break
            // Apparently on macOS EPROTOTYPE can be returned when the socket is not
            // fully shutdown (as an EPIPE would indicate). Here we treat them
            // essentially the same since we just tear the transport down anyway.
            // http://erickt.github.io/blog/2014/11/19/adventures-in-debugging-a-potential-osx-kernel-bug/
            case EPROTOTYPE:
                fallthrough
            case EPIPE:
                closedByPeer()

            default:
                fatalError("Failed to send, errno=\(number), message=\(message)")
            }
        } catch {
            fatalError("Failed to send")
        }

**Comment by Goos** [comment]
Sorry for the silence everyone – I haven't had time to dig any deeper into this issue since last time, but given that it's a small change and seems to work for the people trying it out, I'm going to go ahead and merge this.

**Review by Goos — APPROVED** [review]

**Pull request merged**
